"""project_name_default_to_empty_string

Revision ID: c10f1752f975
Revises: a4893b48c6a1
Create Date: 2026-01-07 09:29:48.667283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10f1752f975'
down_revision: Union[str, None] = 'a4893b48c6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###
